Doha - Terraform initialization
CraftsmenLtd/coe-batch-q322 pull request #197
Opened 2022-08-23 12:33 UTC by DewDropsDoha

Fixes #174 

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done
Terraform initialized following this link
https://learn.hashicorp.com/tutorials/terraform/install-cli?in=terraform/aws-get-started

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 06:53 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/s3bucket.tf
> +  bucket = "doha-terraform-bucket"
S3 bucket name used from env. Commit a4b1752

2022-09-04 06:54 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate
> +{
tfstate file included in gitignore. Commit cdafa92

2022-09-05 06:33 UTC, mhazad commented on doha-aws-node-project/terraform/terraform.tfstate
> +{
And this file needs to be deleted from the Git.

2022-09-05 08:55 UTC, mhazad requested changes
Pls, remove unnecessary files.

2022-09-05 11:24 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate
> +{
tfstate file removed. Commit 9e0f54f
yarn.lock file removed. Commit 52db6fa

2022-09-05 12:27 UTC, mhazad approved these changes
LGTM

2022-09-05 12:27 UTC, merged