Doha - Lambda function added using terraform
CraftsmenLtd/coe-batch-q322 pull request #200
Opened 2022-08-23 12:55 UTC by DewDropsDoha

Fixes #174  #192

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #197 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done
Lambda initialized using terraform. 
Refs: https://learn.hashicorp.com/tutorials/terraform/lambda-api-gateway?in=terraform/aws#create-and-upload-lambda-function-archive

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 06:52 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate
>  {
tfstate files added in gitignore. Commit 34d87b3

2022-09-04 06:52 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate.backup
> +{
tfstate files added in gitignore. Commit 34d87b3

2022-09-05 06:54 UTC, mhazad commented on doha-aws-node-project/terraform/terraform.tfstate
>  {
And then you need to delete the file from git.

2022-09-05 06:54 UTC, mhazad commented on doha-aws-node-project/terraform/terraform.tfstate.backup
> +{
And then you need to delete the file from git.

2022-09-05 08:54 UTC, mhazad requested changes
Pls, remove unnecessary files.

2022-09-05 11:41 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate
>  {
tfstate files removed. Commit 3df427f

2022-09-05 11:41 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate.backup
> +{
tfstate files removed. Commit 3df427f

2022-09-05 12:28 UTC, mhazad approved these changes
LGTM

2022-09-05 12:28 UTC, merged