Doha - API Gateway in Terraform
CraftsmenLtd/coe-batch-q322 pull request #202
Opened 2022-08-23 13:40 UTC by DewDropsDoha

Fixes #174 

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #200

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done
API Gateway (HttpApi) implemented and generated base_url working fine.
Refs: https://learn.hashicorp.com/tutorials/terraform/lambda-api-gateway?_ga=2.267865927.81444029.1661240980-1436054164.1661240980#create-an-http-api-with-api-gateway

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 06:49 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate
>  {
tfstate files added in gitignore. Commit 8c3b2c8

2022-09-04 06:49 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate.backup
> +  "serial": 62,
tfstate files added in gitignore. Commit 8c3b2c8

2022-09-05 06:54 UTC, mhazad commented on doha-aws-node-project/terraform/terraform.tfstate
>  {
And then you need to delete the file from git.

2022-09-05 06:54 UTC, mhazad commented on doha-aws-node-project/terraform/terraform.tfstate.backup
> +  "serial": 62,
And then you need to delete the file from git.

2022-09-05 08:56 UTC, mhazad requested changes
Pls, remove unnecessary files.

2022-09-05 12:05 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate
>  {
tfstate files removed. Commit cdb03c0

2022-09-05 12:05 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform.tfstate.backup
> +  "serial": 62,
terraform.tfstate file removed. Commit cdb03c0

2022-09-05 12:29 UTC, merged