React App Todo-List successfully created following the given requirements
CraftsmenLtd/coe-batch-q322 pull request #220
Opened 2022-08-24 09:15 UTC by DewDropsDoha

Fixes #221

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #236

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done

## Requirements
Create a Todo app using React. The app have following requirements:

1. An input field
(a) when the input field is focused, it shows an indicator that it is focused. Show hover effect on the input field. 
(b) Pressing Enter while focusing on input field after writing the task should add the task on the Task list and defocus the input field
(c) Pressing Escape while focusing on input field will clear the text and defocus the input field.

2. Task List
(a) List of tasks designed with pure css 
(b) Hovering over each of the list items should show a delete button and a completed button.
(c) Clicking the delete button should delete the task item and the completed button should keep the item in the list, but it should be strike-through.

3. Use create-react-app 
4. Use React Functional Component and hooks.
5. Rearrange components and folders in an efficient way. 
6. Use React best patterns

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-01 11:51 UTC, tusher-A requested changes
Requested some minor changes.

2022-09-01 11:51 UTC, tusher-A commented on react/todo-list/src/components/todoList/ToDoList.js
> +import React, { useState } from "react";
This file here seems to be the same file as `TodoList.js` and from index you are exporting. This is totally an unnecessary file. Please remove it.

2022-09-01 11:51 UTC, tusher-A commented on react/todo-list/src/components/todoList/TodoList.js
> +            </button>
You should split this into a separate component for better use. Move this to `components/taskItem` folder with proper structure.

2022-09-02 03:28 UTC, DewDropsDoha commented on react/todo-list/src/components/todoList/TodoList.js
> +            </button>
TodoList split-able code moved to new component taskItem folder.
 Commit: 2a59698

2022-09-02 03:44 UTC, DewDropsDoha commented on react/todo-list/src/components/todoList/ToDoList.js
> +import React, { useState } from "react";
I have renamed the ToDoList.js to TodoList.js. There's no ToDoList.js file in the project. Image referencing no ToDoList.js file in project add to static folder.  Commit 5b4ac9b8

2022-09-02 05:45 UTC, tusher-A requested changes
Still some issues remaining. Please verify.

2022-09-02 05:45 UTC, tusher-A commented on react/todo-list/src/components/todoList/ToDoList.js
> +import React, { useState } from "react";
This file here should be deleted. Please verify.

2022-09-02 05:45 UTC, tusher-A commented on react/todo-list/src/components/todoList/components/taskItem/TaskItem.js
> +  };
You don't need to keep `useEffect` here, as you can see you can directly call the `taskStateSetter` from the `toggleTask` and `removeTask` function. Keeping an extra child state here is unnecessary.

2022-09-02 05:49 UTC, DewDropsDoha commented on react/todo-list/src/components/todoList/ToDoList.js
> +import React, { useState } from "react";
Mentioned file deleted. Commit 350ff391

2022-09-02 05:55 UTC, DewDropsDoha commented on react/todo-list/src/components/todoList/components/taskItem/TaskItem.js
> +  };
useEffect removed. taskStateSetter used in toggleTask and removeTask. Commit f25916f1

2022-09-02 06:38 UTC, tusher-A approved these changes
LGTM.

2022-09-02 06:38 UTC, merged