React Todo App : Emotion UI added
CraftsmenLtd/coe-batch-q322 pull request #247
Opened 2022-08-25 13:52 UTC by shadman0711

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [x] Improvement
- [ ] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Emotion UI elements added

## What was done
* Emotion styled components added

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-01 12:12 UTC, tusher-A requested changes
Some serious issue remains in the code. Please address them.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/App.js
> +import { ContentArea } from './components/ContentArea.styled';
- These two files should not be placed inside `src/components` folder. It doesn't make any sense as you are using it inside `App.js` file.
- Create a file called `App.styled.js` as per your preferred way. Move the `Container` and `ContentArea` there.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/components/Container.styled.js
> +import styled from '@emotion/styled';
Remove this from here. Check comment above.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/components/ContentArea.styled.js
> +import styled from '@emotion/styled';
Remove this from here. Check comment above.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/components/TodoForm/TodoForm.js
> +import { FormInput } from './FormInput.styled';
- I don't understand, why are you creating two separate files to incorporate style into the same component. Does that even make sense to you?
-  Both `FormContainer` or `FormInput` can be place to a single file and you can name it `TodoFrom.styled.js` as per your preferred way. 

Please communicate with your fellow trainee if you don't understand this.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/components/TodoForm/FormContainer.styled.js
> +import styled from '@emotion/styled';
Why single style on single file? I am really confused.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/components/TodoForm/FormInput.styled.js
> +import styled from '@emotion/styled';
Same here again.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/components/Todos/TodoList.styled.js
> +import styled from '@emotion/styled';
Rename the file  to `Todo.styled.js`. Makes more sense.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/components/Todos/components/ListItem/ListItem.js
> +import { DeleteButton } from './DeleteButton.styled';
- Again why you have separate styles in separate files, when you can keep them just in one style file. Please fix this. This is really bad practice.

2022-09-01 12:12 UTC, tusher-A commented on todo-app/src/context/todoContext.js
> +    const [todos, setTodos] = useState([]);
You were asked to use `useReducer` not `useState`. Please redo this.

2022-09-02 05:28 UTC, shadman0711 commented on todo-app/src/context/todoContext.js
> +    const [todos, setTodos] = useState([]);
Added useReducer in commit [39bd531](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/39bd53138800493ff01d43f60c36c57addb8077c)

2022-09-02 05:28 UTC, shadman0711 commented on todo-app/src/App.js
> +import { ContentArea } from './components/ContentArea.styled';
Updated file structure in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:28 UTC, shadman0711 commented on todo-app/src/components/Container.styled.js
> +import styled from '@emotion/styled';
Updated file structure in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:28 UTC, shadman0711 commented on todo-app/src/components/ContentArea.styled.js
> +import styled from '@emotion/styled';
Removed in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:29 UTC, shadman0711 commented on todo-app/src/components/TodoForm/TodoForm.js
> +import { FormInput } from './FormInput.styled';
Updated file structure in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:29 UTC, shadman0711 commented on todo-app/src/components/TodoForm/FormContainer.styled.js
> +import styled from '@emotion/styled';
Changed this in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:29 UTC, shadman0711 commented on todo-app/src/components/TodoForm/FormInput.styled.js
> +import styled from '@emotion/styled';
Updated in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:30 UTC, shadman0711 commented on todo-app/src/components/Todos/TodoList.styled.js
> +import styled from '@emotion/styled';
Renamed in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:30 UTC, shadman0711 commented on todo-app/src/components/Todos/components/ListItem/ListItem.js
> +import { DeleteButton } from './DeleteButton.styled';
Fixed in commit [7717cf6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/247/commits/7717cf6fc05ae0b6266281efbe44e54955b077dc)

2022-09-02 05:50 UTC, tusher-A approved these changes
LGTM.

2022-09-02 05:50 UTC, merged