Converted the serverless to terraform and refactored the both serverless and terraform code
CraftsmenLtd/coe-batch-q322 pull request #256
Opened 2022-08-26 10:17 UTC by ewuharun

Fixes #145 

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #131 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [x] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
I have implemented the terraform task
## What was done
1. s3->sqs
2. sqs->video compression->dynamo
3. dynamo->SNS->Discord
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-02 12:08 UTC, mhazad requested changes
Please address the feedback.

2022-09-02 12:08 UTC, mhazad commented on src/main/java/com/serverless/lambdas/TerraformLambda.java
> +package com.serverless.lambdas;
You are violating DRY. Copying code can be considered the worst possible mistake by a developer. Please delete copied code and reuse the existing one.

2022-09-07 11:14 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/TerraformLambda.java
> +package com.serverless.lambdas;
Deleted the TerraformLambda.java

2022-09-07 12:19 UTC, mhazad approved these changes
LGTM

2022-09-07 12:19 UTC, merged