Add dockerfile and docker-compose to react project
CraftsmenLtd/coe-batch-q322 pull request #280
Opened 2022-08-29 12:58 UTC by shadman0711

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Dockerfile added in the react js project

## What was done
* Dockerfile added
* dockerignore file added

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-02 08:29 UTC, musfique-m approved these changes
Looks good.

2022-09-02 08:29 UTC, musfique-m commented on react-kanban/Dockerfile.prod
> +COPY package-lock.json ./
Just a reminder, you can reduce the number of layer by using wildcard (*) here.
`COPY package*.json ./`

2022-09-02 08:36 UTC, shadman0711 commented on react-kanban/Dockerfile.prod
> +COPY package-lock.json ./
Updated Dockerfile in commit [45a065d](https://github.com/CraftsmenLtd/coe-batch-q322/pull/280/commits/45a065d06e5a969b305d3e5432f479487fbf8b8d)

2022-09-05 14:13 UTC, musfique-m requested changes

2022-09-05 14:13 UTC, musfique-m commented on react-kanban/Dockerfile.prod
> +COPY package-lock.json ./
Please also update this file.

2022-09-06 03:35 UTC, shadman0711 commented
Added wildcard in Dockerfile.prod in commit [149bbd1](https://github.com/CraftsmenLtd/coe-batch-q322/pull/280/commits/149bbd100d1f2dd1ff3943e0f0a5e82d10497714)

2022-09-07 03:58 UTC, musfique-m approved these changes
Looks good.

2022-09-07 03:58 UTC, merged