docker images, container and volume
CraftsmenLtd/coe-batch-q322 pull request #282
Opened 2022-08-29 13:23 UTC by mukutdanielroy

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #225 

## What kind of change does this PR introduce (check at least one)
Dockerfile was created for the todo app.
- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Dockerfile was added where new images can be created.
## What was done

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-03 23:22 UTC, musfique-m requested changes
Please make separate `Dockerfile.prod` & `docker-compose.prod.yml`and move the production code there. In the `docker-compose.prod.yml` make sure it uses the `DockerFile.prod` to build image. In the `Dockerfile` & `docker-compose.yml` just keep the dev version of the docker commands. Also remove comment from prod versions.

2022-09-03 23:22 UTC, musfique-m commented on daniel-todo-app/Dockerfile
> +EXPOSE 80
Please move the expose command before entrypoint.

2022-09-05 20:35 UTC, mukutdanielroy commented on daniel-todo-app/Dockerfile
> +RUN npm install react-scripts@5.0.1 -g --silent
only package*.json kept in next commit.

2022-09-05 20:36 UTC, mukutdanielroy commented
> Please make separate `Dockerfile.prod` & `docker-compose.prod.yml`and move the production code there. In the `docker-compose.prod.yml` make sure it uses the `DockerFile.prod` to build image. In the `Dockerfile` & `docker-compose.yml` just keep the dev version of the docker commands. Also remove comment from prod versions.

all docker files are being seperated.

2022-09-07 04:01 UTC, musfique-m requested changes

2022-09-07 04:01 UTC, musfique-m commented on daniel-todo-app/Dockerfile.prod
> +COPY package.json ./
Please also use wild card here.

2022-09-07 04:39 UTC, mukutdanielroy commented on daniel-todo-app/Dockerfile.prod
> +COPY package.json ./
wild card was added in the next commit.

2022-09-07 17:47 UTC, musfique-m approved these changes
Looks good.

2022-09-07 17:47 UTC, merged