Added Dockerfile
CraftsmenLtd/coe-batch-q322 pull request #283
Opened 2022-08-29 13:26 UTC by faisalisafk

Fixes 

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Added docker file and dockerignore file
## What was done
- Created Dockerfile and .dockerignore file for docker implementation
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 18:03 UTC, musfique-m requested changes

2022-09-04 18:03 UTC, musfique-m commented on faisal/todo/Dockerfile
> +COPY package-lock.json .
Please use wild card here to copy both files by i command. It will reduce the no of layers.

2022-09-05 06:53 UTC, faisalisafk commented on faisal/todo/Dockerfile
> +COPY package-lock.json .
added wildcard for reducing layers

2022-09-07 04:02 UTC, musfique-m approved these changes

2022-09-07 04:02 UTC, merged