building docker image to run react app on cntainer
CraftsmenLtd/coe-batch-q322 pull request #284
Opened 2022-08-29 13:32 UTC by hossainahmed18

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [x] Improvement
- [ ] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done

Dockerize the previously build todo-app of react. A Dockerfile created and a dockerignore. necessary changes are made to build a docker image and run it on docker container

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-02 07:19 UTC, musfique-m requested changes

2022-09-02 07:19 UTC, musfique-m commented on junayed-task/todo-docker/.dockerignore
> +src/App.test.js
There is no need add test files to dockerignore.
Later we may decide to run the test from our image. We won't be able to do that in this case.
Please remove the test file from here.

2022-09-02 07:19 UTC, musfique-m commented on junayed-task/todo-docker/Dockerfile
> +COPY package.json .
Please also copy `package-lock.json`. Its goal is to keep track of exact version of the package installed.
[Further information](https://nodejs.dev/en/learn/the-package-lock-json-file/)

2022-09-02 08:31 UTC, hossainahmed18 commented on junayed-task/todo-docker/.dockerignore
> +src/App.test.js
resolved

2022-09-02 08:31 UTC, hossainahmed18 commented on junayed-task/todo-docker/Dockerfile
> +COPY package.json .
resolved

2022-09-07 04:08 UTC, musfique-m approved these changes
Looks good. Approved by code inspection.

2022-09-07 04:08 UTC, merged