React/Kanban Board
CraftsmenLtd/coe-batch-q322 pull request #290
Opened 2022-08-30 04:55 UTC by Awsaf780

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- Add tasks to Kanban Board
- Drag and Drop tasks between boards
- Toggle Theme

## What was done
- Use Context API and useReducer to manage global state
- Toggle Theme change between Light and Dark on click
- Maintain count of items in each board
- Use Emotion styled components
- Use React-dnd to implement drag and drop functionality
- Organize file structure will small components

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-01 22:08 UTC, Awsaf780 commented on react/kanban-board/src/App.js
> +        <AppDiv>
Resolved in commit [04495fb](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/04495fb29341be75828282403f61d6e00ac16c73)

2022-09-01 22:08 UTC, Awsaf780 commented on react/kanban-board/src/contexts/State.js
> +    }
Resolved in commit [cbcb445](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/cbcb445d7dcb9950e8dc6a7b682f92e581983b71)

2022-09-01 22:09 UTC, Awsaf780 commented on react/kanban-board/src/contexts/State.js
> +        countDone: 0,
Revolved in commit [9331c69](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/9331c6964014d8ccfbe6ce8f29fa59dc3cd1ae5b)

2022-09-01 22:09 UTC, Awsaf780 commented on react/kanban-board/src/components/home/components/kanban/section/KanbanSection.js
> +  }
Revolved in commit [9331c69](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/9331c6964014d8ccfbe6ce8f29fa59dc3cd1ae5b)

2022-09-01 22:10 UTC, Awsaf780 commented on react/kanban-board/src/contexts/State.js
> +        }
Resolved in commit [4c507bf](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/4c507bfaee45926710999a29c26e2258e328c331)

2022-09-01 22:10 UTC, Awsaf780 commented on react/kanban-board/src/components/home/components/kanban/KanbanBoard.js
> +        <KanbanSection type={'In Progress'} status={'inProgress'}/>
[2c97f0b](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/2c97f0b742c68f88fb6ef0f91a67a8d06f8c7960)

2022-09-01 22:10 UTC, Awsaf780 commented on react/kanban-board/src/components/home/components/kanban/section/components/taskList/TaskList.js
> +  }
Resolved in commit [3afe5d6](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/3afe5d637a7acc805bbd074304528a11128ade0b)

2022-09-02 06:33 UTC, tusher-A requested changes
Some changes are requested.

2022-09-02 06:33 UTC, tusher-A commented on react/kanban-board/src/contexts/Reducer.js
> +      };
This should be removed.

2022-09-02 06:33 UTC, tusher-A commented on react/kanban-board/src/contexts/Reducer.js
> +        };
Should use proper enum

2022-09-02 06:54 UTC, Awsaf780 commented on react/kanban-board/src/contexts/Reducer.js
> +      };
Resolved in commit - [e35d5fc](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/e35d5fce310e06442df81422bf1722629caee639)

2022-09-02 06:54 UTC, Awsaf780 commented on react/kanban-board/src/contexts/Reducer.js
> +        };
Resolved in commit - [e35d5fc](https://github.com/CraftsmenLtd/coe-batch-q322/pull/290/commits/e35d5fce310e06442df81422bf1722629caee639)

2022-09-19 07:48 UTC, tusher-A approved these changes
LGTM

2022-09-19 07:48 UTC, merged