Added compose prod and dockerfile prod
CraftsmenLtd/coe-batch-q322 pull request #295
Opened 2022-08-30 13:02 UTC by faisalisafk

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #283

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Added Docker file and docker compose file to create volume and implement multi stage build
## What was done
- Added Dockerfile and docker-compose.yml to create container with a volume binding of todo app
- Added Dockerfile.prod and docker-compose.prod.yml to create multi stage container of build file and nginx
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 21:49 UTC, musfique-m requested changes

2022-09-04 21:49 UTC, musfique-m commented on faisal/todo/Dockerfile
> +COPY package-lock.json .
Please use wildcard here to copy both files in one go. This way we can reduce the number of layers.

2022-09-04 21:49 UTC, musfique-m commented on faisal/todo/Dockerfile.prod
> +COPY package-lock.json .
Please also use wildcard here.

2022-09-04 21:49 UTC, musfique-m commented on faisal/docker-compose.prod.yml
> +      stdin_open: true
Why are we running our production container in interactive mode?

2022-09-05 07:22 UTC, faisalisafk commented on faisal/todo/Dockerfile
> +COPY package-lock.json .
Added wildcards in [c1482ff](https://github.com/CraftsmenLtd/coe-batch-q322/pull/295/commits/c1482ff80747ef39ca4e5c28aace8964c5bb128b)

2022-09-05 07:22 UTC, faisalisafk commented on faisal/todo/Dockerfile.prod
> +COPY package-lock.json .
Added wildcards in [c1482ff](https://github.com/CraftsmenLtd/coe-batch-q322/pull/295/commits/c1482ff80747ef39ca4e5c28aace8964c5bb128b)

2022-09-05 07:23 UTC, faisalisafk commented on faisal/docker-compose.prod.yml
> +      stdin_open: true
I have removed interactive mode in [c1482ff](https://github.com/CraftsmenLtd/coe-batch-q322/pull/295/commits/c1482ff80747ef39ca4e5c28aace8964c5bb128b) .

2022-09-07 04:11 UTC, musfique-m approved these changes
Looks good.

2022-09-07 04:11 UTC, merged