docker compose with multi stage
CraftsmenLtd/coe-batch-q322 pull request #296
Opened 2022-08-30 13:06 UTC by hossainahmed18

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done

docker compose files are introduced. Firstly, files are changed to build a docker image and run react app on container. Then in next step docker compose files are changed for multi stage deployment. React app will be deployed on nginx server

## How to test

- [x] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 23:26 UTC, musfique-m requested changes

2022-09-04 23:26 UTC, musfique-m commented on junayed-task/todo-docker/Dockerfile.prod
> +Expose 4200
Why are port 4200 exposed here?
nginx listens to port 80 by default. This EXPOSE instruction should indicate what ports are we gonna get our output from this Dockerfile.

2022-09-04 23:26 UTC, musfique-m commented on junayed-task/todo-docker/Dockerfile.prod
> +COPY package.json .
Please also copy `package-lock.json` to keep track of the exact version of every package that is installed.
Also use wild card to reduce the number of layers.

Also please remove comments from prod files.

2022-09-05 02:49 UTC, hossainahmed18 commented on junayed-task/todo-docker/Dockerfile.prod
> +Expose 4200
In docker-compose file I mapped port 80 to 4200. That's why I exposed it to 4200. 
![image](https://user-images.githubusercontent.com/43014424/188351310-99a0cc54-5a85-4388-921c-7d1887058b6f.png)

2022-09-05 02:51 UTC, hossainahmed18 commented on junayed-task/todo-docker/Dockerfile.prod
> +COPY package.json .
resolved with commit : https://github.com/CraftsmenLtd/coe-batch-q322/pull/296/commits/ac7c4bacd21678cf74b4a54489cdb73a54b2228f

2022-09-07 17:57 UTC, musfique-m requested changes
Please look at the comment about port expose.

Also remove comment from prod files.

2022-09-07 17:57 UTC, musfique-m commented on junayed-task/todo-docker/Dockerfile.prod
> +Expose 4200
This expose indicates the port that we are going to listen to in the container. The container is run from an image that is built with the help of this Dockerfile. So we should always EXPOSE the port here that we are going to use. In this case it is 80, not 4200. In our docker-compose we are just mapping port 4200 of the host os to the port 80 of this container. We can map that to many ports as we want. But our container built from our image will only be accessible by the port 80 of the container.

2022-09-07 17:58 UTC, musfique-m commented on junayed-task/todo-docker/Dockerfile.prod
> +Expose 4200
Please look at the comment.

2022-09-08 02:56 UTC, hossainahmed18 commented on junayed-task/todo-docker/Dockerfile.prod
> +Expose 4200
resolved with last commits

2022-09-11 16:42 UTC, musfique-m requested changes

2022-09-12 03:15 UTC, hossainahmed18 commented on junayed-task/todo-docker/Dockerfile.prod
> +Expose 80
resolved with commit : https://github.com/CraftsmenLtd/coe-batch-q322/pull/296/commits/9ec4d96fbc62067fb935f4001670feab63f2e85b

2022-09-12 03:16 UTC, hossainahmed18 commented on junayed-task/todo-docker/Dockerfile
> +Expose 3000
resolved with commit: https://github.com/CraftsmenLtd/coe-batch-q322/pull/296/commits/9ec4d96fbc62067fb935f4001670feab63f2e85b

2022-09-13 11:43 UTC, musfique-m approved these changes
Looks good.

2022-09-13 11:43 UTC, merged