Docker/MultiPart Stage Build
CraftsmenLtd/coe-batch-q322 pull request #297
Opened 2022-08-30 13:17 UTC by Awsaf780

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Serve react application with NGINX

## What was done
- Create docker-compose.prod file to configure NGINX 
- Change npm start to npm build
- Copy build files to nginx html directory
- Remove files other than build to decrease image size
- Expose on port 8080

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 22:59 UTC, musfique-m requested changes

2022-09-05 20:04 UTC, Awsaf780 commented on react/todo-app/Dockerfile
> +COPY package.json .
Resolved in commit [8133ca9](https://github.com/CraftsmenLtd/coe-batch-q322/pull/297/commits/8133ca9f0bad832b840d541eaa94838f73fbbe99)

2022-09-07 18:42 UTC, musfique-m requested changes

2022-09-07 18:42 UTC, musfique-m commented on react/todo-app/docker-compose.prod.yml
> +      stdin_open: true
Please remove this. We don't want to run our production container in interactive mode by default.

2022-09-08 00:00 UTC, Awsaf780 commented on react/todo-app/docker-compose.prod.yml
> +      stdin_open: true
Removed in commit [59fb32a](https://github.com/CraftsmenLtd/coe-batch-q322/pull/297/commits/59fb32ae0a5d6673249da0e92ade7f7c5267af00)

2022-09-11 17:25 UTC, musfique-m approved these changes
Looks good.

2022-09-11 17:27 UTC, merged