Nayem ddb query
CraftsmenLtd/coe-batch-q322 pull request #298
Opened 2022-08-30 14:43 UTC by lucifer7663

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #234  

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- dynamodb query is implemented in this branch
## What was done
- user or customer can query in dynamodb through api call and will get response in return.
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-02 09:50 UTC, mhazad requested changes
Please address the feedback.

2022-09-02 09:50 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +            itemvalues.put("GSI1Sk", new AttributeValue(customerName + "_" + dateStr));
It's a good practice to have a utility method to get the PK/SK/GsiPK/GsiSK like getPkOfCustomerActivity(), GetGsiSkOfCustomerActivity() etc

The benefit is that we shall get information about key formation from a single place so it will act as documentation. Also If we ever need to change any key formation in the future then we need to change in a single place.

2022-09-02 09:50 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +            itemvalues.put("GSI1Sk", new AttributeValue(customerName + "_" + dateStr));
Do the changes in all the places where you have used any of these keys.

2022-09-02 09:50 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +                    webb.post("webhooks/1004259809731821648/_oZdyC2RsXmdQdFieddS39Y1wUb4HXDu4YOshU-EK6qwzTRpO9oo__zcOGjtMqO0FGzE")
Why we are using hard-coded values here?

2022-09-02 09:50 UTC, mhazad commented on src/main/java/com/serverless/ObjectParsing.java
> +    public JSONObject getBodyObject (Map<String, Object> recordsMap){
What is the reason of having a space between getBodyObject and ( ?

2022-09-02 09:50 UTC, mhazad commented on src/main/java/com/serverless/ObjectParsing.java
> +            return  bodyJsonObject;
Why did you add an extra space before `bodyJsonObject`?

2022-09-02 09:50 UTC, mhazad commented on src/main/java/com/serverless/ObjectParsing.java
> +        }else {
bad code formatting.

2022-09-02 09:50 UTC, mhazad commented on terraform/terraform_sqs.tf
> +        "Resource" : "arn:aws:sqs:*:*:nayem-craftsmen-sqs-terraform",
this `nayem-craftsmen-sqs-terraform` needs to be come from env

2022-09-06 15:42 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +                    webb.post("webhooks/1004259809731821648/_oZdyC2RsXmdQdFieddS39Y1wUb4HXDu4YOshU-EK6qwzTRpO9oo__zcOGjtMqO0FGzE")
environment variable is introduced instead of hard code

2022-09-06 15:43 UTC, lucifer7663 commented on src/main/java/com/serverless/ObjectParsing.java
> +    public JSONObject getBodyObject (Map<String, Object> recordsMap){
spacing is now fixed

2022-09-06 15:43 UTC, lucifer7663 commented on src/main/java/com/serverless/ObjectParsing.java
> +            return  bodyJsonObject;
spacing is fixed

2022-09-06 15:43 UTC, lucifer7663 commented on terraform/terraform_sqs.tf
> +        "Resource" : "arn:aws:sqs:*:*:nayem-craftsmen-sqs-terraform",
it is now in environment varriable

2022-09-07 05:09 UTC, mhazad requested changes
Please address the feedback.

2022-09-07 05:09 UTC, mhazad commented on serverless.yml
> +          method: post
Why do we need to use POST method for doing query? Will it do any kind of data mutation? Please explain.

2022-09-07 05:09 UTC, mhazad commented on serverless.yml
> +
What is the benefit of having 5 extra new lines here?

2022-09-07 05:09 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +
Why an extra new line is needed here?

2022-09-07 05:09 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +
Unnecessary new line.

2022-09-07 05:09 UTC, mhazad commented on terraform/terraform_sqs.tf
> +        "Resource" : "arn:aws:sqs:*:*:${var.nayem_sqs_name}",
This PR is supposed to deal with only DDB queries. Why did you add changes related to Terraform?

2022-09-07 05:47 UTC, lucifer7663 commented on terraform/terraform_sqs.tf
> +        "Resource" : "arn:aws:sqs:*:*:${var.nayem_sqs_name}",
it is requested to change in previous review

2022-09-07 05:49 UTC, lucifer7663 commented on serverless.yml
> +          method: post
because I was passing data in the body, so used post method

2022-09-07 06:04 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +
removed in current commit

2022-09-07 06:04 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +
removed in current commit

2022-09-07 10:33 UTC, lucifer7663 commented on serverless.yml
> +          method: post
as there is no data mutation thus changed the method to get

2022-09-07 12:12 UTC, mhazad requested changes
I have some more feedback. Please address these.

2022-09-07 12:12 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
What will happen if table.query(spec) encounters an error?

2022-09-07 12:12 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
What will happen if table.query(spec) encounters an error?

2022-09-07 12:12 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
What will happen if table.query(spec) encounters an error?

2022-09-07 12:12 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = index.query(spec);
What will happen if table.query(spec) encounters an error?

2022-09-07 13:00 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
the program will be crashed. thus enclosed the code in try catch block

2022-09-07 13:01 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
the program will be crashed. thus enclosed the code in try catch block

2022-09-07 13:01 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
the program will be crashed. thus enclosed the code in try catch block

2022-09-07 13:01 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +                    ItemCollection<QueryOutcome> items = index.query(spec);
the program will be crashed. thus enclosed the code in try catch block

2022-09-07 13:13 UTC, mhazad commented on terraform/terraform_sqs.tf
> +        "Resource" : "arn:aws:sqs:*:*:${var.nayem_sqs_name}",
A previous review of this particular PR?

2022-09-09 23:25 UTC, closed without merging