Docker task 2 Eftakhar
CraftsmenLtd/coe-batch-q322 pull request #299
Opened 2022-08-31 00:38 UTC by shoccho

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Inclueded dockercompose file and added two variants of docker file and docker compose
## What was done
Added docker-compose.yml for basic react deployment
Added Dockerfile.prod for new nginx deployment
Added docker-compose.prod for nginx deployment 
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-03 20:54 UTC, musfique-m requested changes
Please take a look at the comment to copy package-lock.json.
Please also remove comments from Dockerfile.prod.

2022-09-03 20:54 UTC, musfique-m commented on frontend/react-client/Dockerfile.prod
> +COPY package.json .
Please also copy `package-lock.json`.

2022-09-05 02:58 UTC, shoccho commented on frontend/react-client/Dockerfile.prod
> +COPY package.json .
Resolved this in the commit [bfb8ccd](https://github.com/CraftsmenLtd/coe-batch-q322/pull/299/commits/bfb8ccd7dae9ae29b4b1c6cfb1d374bfa3cb0547)

2022-09-07 04:49 UTC, musfique-m approved these changes
Looks good.

2022-09-07 04:49 UTC, merged