polok docker task 1
CraftsmenLtd/coe-batch-q322 pull request #300
Opened 2022-08-31 03:35 UTC by codefresher32

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- Building docker image & run container

## What was done
- Created a docker file
- Docker file created in such a way that it is optimized
- For each line in docker file comment added like ased

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 18:47 UTC, musfique-m requested changes

2022-09-04 18:47 UTC, musfique-m commented on react_client/todo/Dockerfile
> +COPY package.json .
Please also copy package-lock.json also to keep track of the exact version of every package that is installed.
Also use wild card to reduce the number of layers.

2022-09-05 02:23 UTC, codefresher32 commented on react_client/todo/Dockerfile
> +COPY package.json .
Added package-lock.json as wildcard....

2022-09-05 14:34 UTC, musfique-m requested changes
Please remove the files that are not related to docker from this pr.
**Only** docker related files should be a part of this pr.

2022-09-06 03:02 UTC, codefresher32 commented
> Please remove the files that are not related to docker from this pr. **Only** docker related files should be a part of this pr.

Vi, I just organized the file structure for conflicts issue for merging in react-master branch. As I am copying all the files in dockerfile, I think I need all the files. Can you tell me what I miss?

2022-09-07 18:12 UTC, musfique-m commented
> > Please remove the files that are not related to docker from this pr. **Only** docker related files should be a part of this pr.
> 
> Vi, I just organized the file structure for conflicts issue for merging in react-master branch. As I am copying all the files in dockerfile, I think I need all the files. Can you tell me what I miss?

In the `File Changed` section of this pr you can see that there are 21 files changed. If we proceed to merge this branch with the master, all of this file change will be blamed under this pr. That git blame will be almost useless. It will convey little to no information ( sometimes misinformation ) about why these files were changed. 

In the merge conflict, probably you have introduces some new changes while merging with master branch was being done. It resulted in the increase of the number of file changed. This pr should only consist of files that are related to docker.

2022-09-08 03:11 UTC, codefresher32 commented
Thank you vi. I understand it now. Reverted the commit. Please review this pr.

2022-09-13 11:50 UTC, merged