Docker compose multi stage
CraftsmenLtd/coe-batch-q322 pull request #302
Opened 2022-08-31 03:39 UTC by DewDropsDoha

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done
Our Todo-app built and served from nginx. First stage is our app and second stage is nginx which copies first stage build files then run it.

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 21:38 UTC, musfique-m requested changes
Please move docker-compose files somewhere in the parent directories as later we may want to run more app at the same time using the same docker-compose files.

2022-09-04 21:38 UTC, musfique-m commented on react/todo-list/Dockerfile
> +COPY package.json .
Please also copy `package-lock.json` to keep track of the exact version of every package that is installed.
Also use wild card to reduce the number of layers.

2022-09-04 21:38 UTC, musfique-m commented on react/todo-list/Dockerfile.prod
> +COPY package.json .
Please also copy package-lock.json.

2022-09-04 21:38 UTC, musfique-m commented on react/todo-list/docker-composer.prod.yml
> +      stdin_open: true
Why are we running our container in interactive mode in production? Please remove it if nnot necessary.

2022-09-04 21:38 UTC, musfique-m commented on react/todo-list/docker-composer.prod.yml
> +          - CHOKIDAR_USEPOLLING=true
In production we don't need to watch for file changes. Please remove this.

2022-09-04 21:38 UTC, musfique-m commented on react/todo-list/docker-composer.prod.yml
> +        - doha:/app
This volume mapping is not necessary in production for our case. What is the purpose here?
Here we are not using it for anything useful. Please remove it.

2022-09-06 02:28 UTC, DewDropsDoha commented on react/todo-list/Dockerfile
> +COPY package.json .
Copied package-lock.json and used wildcard. Commit f9b96f1
I have confusion. Is ["package.json", "package-lock.json", "./"] is proper wildcard?

2022-09-06 02:29 UTC, DewDropsDoha commented on react/todo-list/Dockerfile.prod
> +COPY package.json .
Copied package.json and used wildcard. Commit 5f73831

2022-09-06 02:29 UTC, DewDropsDoha commented on react/todo-list/docker-composer.prod.yml
> +      stdin_open: true
Removed unnecessary code. Commit 27f1226

2022-09-06 02:30 UTC, DewDropsDoha commented on react/todo-list/docker-composer.prod.yml
> +        - doha:/app
Unnecessary volume mapping removed. Commit 5bc74d4

2022-09-06 02:30 UTC, DewDropsDoha commented on react/todo-list/docker-composer.prod.yml
> +          - CHOKIDAR_USEPOLLING=true
Polling-mode watcher removed. Commit 63e4faf

2022-09-07 05:19 UTC, musfique-m commented on react/todo-list/Dockerfile
> +COPY package.json .
This way you can copy multiple files in one go. Suppose you also want to add `README.md` in this then you could write somehting like this `["package.json", "README.md", "./"]`. It will copy both package.json and README.md file to out working directory.

This is ok for now. For our case I suggest that you use something like `COPY ["package*.json", "./"]`.

2022-09-07 05:22 UTC, musfique-m requested changes
The file names should be `docker-compose.yml` and `docker-compose.prod.yml`. Please fix them.

2022-09-07 07:12 UTC, musfique-m approved these changes

2022-09-07 07:18 UTC, merged

2022-09-07 09:06 UTC, DewDropsDoha commented on react/todo-list/Dockerfile
> +COPY package.json .
Thanks for the suggestion. I'll follow the suggested way.