raiyan: run react app using docker.
CraftsmenLtd/coe-batch-q322 pull request #306
Opened 2022-08-31 05:36 UTC by raiyan-hosn

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Added docker to run React todo app.
## What was done

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 18:57 UTC, musfique-m requested changes
Please remove the other files that are not related to Docker from this PR.

2022-09-04 18:57 UTC, musfique-m commented on todo-react-app/Dockerfile
> +COPY . .
Please copy the files after we install packages using npm install. There will be less frequent changes in package-lock files and so we can take advantages of docker caching from here.
Our program files will change more frequently, so every time we build an image the COPY instruction will create a new layer. So caching will not be applied in that case. If you keep your instructions in this order docker will install the packages in every build.

2022-09-05 13:37 UTC, raiyan-hosn commented on todo-react-app/Dockerfile
> +COPY . .
Resolved.

2022-09-07 05:40 UTC, musfique-m requested changes

2022-09-07 05:40 UTC, musfique-m commented on todo-react-app/Dockerfile
> +# coping package-lock.json to app/ dir.
Please reduce the copy operation into a single layer.

2022-09-07 06:00 UTC, raiyan-hosn commented on todo-react-app/Dockerfile
> +# coping package-lock.json to app/ dir.
Reduced copy operation.

2022-09-07 18:32 UTC, musfique-m approved these changes
Looks good.

2022-09-07 18:32 UTC, merged