Graphql/Activity API implement in AppSync
CraftsmenLtd/coe-batch-q322 pull request #309
Opened 2022-08-31 08:34 UTC by arnabrahman

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #308 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Activity API implement in AppSync
## What was done
* Appsync serverless plugin installed
*  Schema created for graphql
*  Resolver created for graphql query & mutation 
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-01 09:40 UTC, arnabrahman commented on lambda/mapping-templates/Query.searchActivity.request.vtl
> +#end
Fixed [34583b2](https://github.com/CraftsmenLtd/coe-batch-q322/pull/309/commits/34583b2c1813bc0406b765a2eec222c0565ca9b9)

2022-09-01 09:40 UTC, arnabrahman commented on lambda/mapping-templates/Query.searchActivity.request.vtl
> +          ":PK" : {"S":"$PK"},
Fixed [0dd88a4](https://github.com/CraftsmenLtd/coe-batch-q322/pull/309/commits/0dd88a4ba8a8f8e7c44c73ae1d9dd32a4679a03d)

2022-09-01 09:40 UTC, arnabrahman commented on lambda/schema.graphql
> +}
Fixed [3ca6e51](https://github.com/CraftsmenLtd/coe-batch-q322/pull/309/commits/3ca6e515cfaabd4f79b26dc8ebea35da49f89f90) [a975ab8](https://github.com/CraftsmenLtd/coe-batch-q322/pull/309/commits/a975ab8cc23615092fe4cdd4409958bad464ec7d)

2022-09-01 09:40 UTC, arnabrahman commented on lambda/schema.graphql
> +	createActivityByLambda(input: ActivitySaveMutationInput): createActivityByLambdaResponse
Fixed [3ca6e51](https://github.com/CraftsmenLtd/coe-batch-q322/pull/309/commits/3ca6e515cfaabd4f79b26dc8ebea35da49f89f90)

2022-09-02 05:29 UTC, rkzico21 commented on lambda/mapping-templates/Query.searchActivityByLambda.response.vtl
> +}
This can be simpler like what have been done for dynamo resolver.

2022-09-02 05:32 UTC, rkzico21 requested changes
I minor feedback. Apart from that everything looks fine.

2022-09-02 06:06 UTC, arnabrahman commented on lambda/mapping-templates/Query.searchActivityByLambda.response.vtl
> +}
> This can be simpler like what have been done for dynamo resolver.

Will do.

2022-09-04 06:11 UTC, arnabrahman commented on lambda/mapping-templates/Query.searchActivityByLambda.response.vtl
> +}
Fixed [3aa7d66](https://github.com/CraftsmenLtd/coe-batch-q322/pull/309/commits/3aa7d660ba5efa4f085e5bfb31cf837fe590fad9)

2022-09-04 06:33 UTC, rkzico21 approved these changes
Good work.

2022-09-04 06:33 UTC, merged