Terraform - Add SNS, SQS, ffmpeg layer
CraftsmenLtd/coe-batch-q322 pull request #310
Opened 2022-08-31 08:38 UTC by shadman0711

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #191 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Terraform configuration for SNS, SQS, Lambda layer added

## What was done
* SNS added
* SQS added
* FFMPEG Lambda Layer Added

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-02 09:43 UTC, mhazad requested changes
Please address the feedback.

2022-09-02 09:43 UTC, mhazad commented on terraform/.terraform.tfstate.lock.info
> +{"ID":"1f44a41c-8cd3-869c-4472-e1140cbe8c4c","Operation":"OperationTypePlan","Info":"","Who":"craftsmen2@craftsmen-Latitude-E6530","Version":"1.2.7","Created":"2022-08-30T08:20:05.651233219Z","Path":
This should not be part of the git

2022-09-02 09:43 UTC, mhazad commented on terraform/lambdas.tf
> +      WEBHOOK_URL         = "https://discord.com/api/webhooks/1004259721424941076/Xo4Lntkm0yycgx1uXkAZ8rh6EonlWfw6Rb6ukBlGI4-sW4lkF5FwvfJnDzkmZtdwWV_d"
These should be read from the environment.

2022-09-02 09:43 UTC, mhazad commented on terraform/sqs.tf
> +  # https://aws.amazon.com/premiumsupport/knowledge-center/sqs-s3-event-notification-sse/
What is the purpose of this commented out code?

2022-09-02 09:53 UTC, shadman0711 commented on terraform/lambdas.tf
> +      WEBHOOK_URL         = "https://discord.com/api/webhooks/1004259721424941076/Xo4Lntkm0yycgx1uXkAZ8rh6EonlWfw6Rb6ukBlGI4-sW4lkF5FwvfJnDzkmZtdwWV_d"
Removed this file in commit [e5917b2](https://github.com/CraftsmenLtd/coe-batch-q322/pull/310/commits/e5917b2eec774b5eee6db22061fcb4e0f82fa936)

2022-09-02 09:53 UTC, shadman0711 commented on terraform/sqs.tf
> +  # https://aws.amazon.com/premiumsupport/knowledge-center/sqs-s3-event-notification-sse/
Removed commented code in [e5917b2](https://github.com/CraftsmenLtd/coe-batch-q322/pull/310/commits/e5917b2eec774b5eee6db22061fcb4e0f82fa936)

2022-09-02 09:53 UTC, shadman0711 commented on terraform/.terraform.tfstate.lock.info
> +{"ID":"1f44a41c-8cd3-869c-4472-e1140cbe8c4c","Operation":"OperationTypePlan","Info":"","Who":"craftsmen2@craftsmen-Latitude-E6530","Version":"1.2.7","Created":"2022-08-30T08:20:05.651233219Z","Path":
Removed this file in commit [e5917b2](https://github.com/CraftsmenLtd/coe-batch-q322/pull/310/commits/e5917b2eec774b5eee6db22061fcb4e0f82fa936)

2022-09-02 09:54 UTC, shadman0711 commented on terraform/lambdas.tf
> +      WEBHOOK_URL         = "https://discord.com/api/webhooks/1004259721424941076/Xo4Lntkm0yycgx1uXkAZ8rh6EonlWfw6Rb6ukBlGI4-sW4lkF5FwvfJnDzkmZtdwWV_d"
Added webhook url variable in commit [e5917b2](https://github.com/CraftsmenLtd/coe-batch-q322/pull/310/commits/e5917b2eec774b5eee6db22061fcb4e0f82fa936)

2022-09-05 05:21 UTC, mhazad approved these changes
LGTM

2022-09-05 05:21 UTC, merged