Docker: task1- build image & run container
CraftsmenLtd/coe-batch-q322 pull request #311
Opened 2022-08-31 09:42 UTC by musfiksifat

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Created docker file to build image & run container

## What was done
- Created docker, docker-ignore file
- Docker file created in optimized way
- Comment added for each line in the docker file 

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-03 23:31 UTC, musfique-m requested changes

2022-09-03 23:31 UTC, musfique-m commented on react_client/todo_app/Dockerfile
> +RUN npm run build
This is an unnecessary step. We are just building our app here and not using it. This is a waste of computational resources and it will increase the time to build our image.
Please remove this layer altogether.

2022-09-04 10:14 UTC, musfiksifat commented on react_client/todo_app/Dockerfile
> +RUN npm run build
removed unnecessary part by commit [764b23e](https://github.com/CraftsmenLtd/coe-batch-q322/pull/311/commits/764b23eb2b3ed92af8e2fe5e5237411d4e7c4afa)

2022-09-04 23:44 UTC, musfique-m approved these changes

2022-09-07 05:23 UTC, merged