Docker Task -1 - Docker image creating and running docker container.
CraftsmenLtd/coe-batch-q322 pull request #313
Opened 2022-08-31 10:23 UTC by D-sourav-M044

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [X] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Docker image has been built and used container to run the todo project.
## What was done
- New docker image has been created in optimized way. Required comments has been placed with the Dockerfile.
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 19:00 UTC, musfique-m requested changes

2022-09-04 19:00 UTC, musfique-m commented on Todo-List-App/Dockerfile
> +COPY package.json .
Please also copy `package-lock.json` also to keep track of the exact version of every package that is installed.
Also use wild card to reduce the number of layers.

2022-09-05 06:59 UTC, D-sourav-M044 commented on Todo-List-App/Dockerfile
> +COPY package.json .
Updated the code to include package-lock.json using wild card. [250d48f](https://github.com/CraftsmenLtd/coe-batch-q322/commit/250d48f290df8e41352e049ebab03b9618883842)

2022-09-07 05:42 UTC, musfique-m approved these changes
Looks good.

2022-09-07 05:42 UTC, merged