Docker: task2-nginx
CraftsmenLtd/coe-batch-q322 pull request #314
Opened 2022-08-31 10:30 UTC by musfiksifat

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #311 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Added docker-compose & docker-compose-prod file and added two variants of docker file

## What was done
- Added docker-compose.yml for normal app deployment
- Added Dockerfile.prod & docker-compose.prod.yml for nginx deployment

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 00:00 UTC, musfique-m requested changes
Please move the docker-compose*yml files to the parent folders. As later we may decide to run multiple app with the same time using docker-compose.
Also please remove the comments from the prod files.

2022-09-04 14:06 UTC, musfiksifat commented on react_client/todo_app/Dockerfile.prod
> +EXPOSE 8080
moved expose command, commit: [51d18f0](https://github.com/CraftsmenLtd/coe-batch-q322/pull/314/commits/51d18f0d2c691d224cd47a8eaf51052849f4dba2)

2022-09-04 14:07 UTC, musfiksifat commented
> Please move the docker-compose*yml files to the parent folders. As later we may decide to run multiple app with the same time using docker-compose. Also please remove the comments from the prod files.

resolved by commit [51d18f0](https://github.com/CraftsmenLtd/coe-batch-q322/pull/314/commits/51d18f0d2c691d224cd47a8eaf51052849f4dba2)

2022-09-07 05:25 UTC, musfique-m approved these changes
Looks good.

2022-09-07 05:37 UTC, merged