polok docker task 2
CraftsmenLtd/coe-batch-q322 pull request #315
Opened 2022-08-31 10:53 UTC by codefresher32

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #300 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- Running todo app both in normul build and production build

## What was done
- Added compose yml both for normul & production build
- Added diiferent dockerfile for normul & production build

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 23:12 UTC, musfique-m requested changes

2022-09-04 23:12 UTC, musfique-m commented on react_client/todo/Dockerfile.prod
> +COPY package.json .
Please also copy `package-lock.json` to keep track of the exact version of every package that is installed.
Also use wild card to reduce the number of layers.

2022-09-05 02:24 UTC, codefresher32 commented on react_client/todo/Dockerfile.prod
> +COPY package.json .
Added package-lock.json as wildcard....

2022-09-08 03:11 UTC, codefresher32 commented
Reverted the commit. Please review this pr.

2022-09-13 11:50 UTC, musfique-m approved these changes
Looks good.

2022-09-13 11:50 UTC, merged