Adding docker compose file for both development and production
CraftsmenLtd/coe-batch-q322 pull request #316
Opened 2022-08-31 11:14 UTC by D-sourav-M044

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #313 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [X] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Docker compose file for development and production has been added.
## What was done
- Static files were built and copied to the nginx server. Created two different docker-compose for development and production.
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-04 21:23 UTC, musfique-m requested changes
Please look at the comments.
Also please remove comments from `Dockerfile.prod`.

2022-09-04 21:23 UTC, musfique-m commented on Todo-List-App/Dockerfile.prod
> +COPY package.json .
Please also copy `package-lock.json` also to keep track of the exact version of every package that is installed.
Also use wild card to reduce the number of layers.

2022-09-04 21:23 UTC, musfique-m commented on Todo-List-App/Dockerfile.prod
> +EXPOSE 3000
Why are port 3000 exposed here?
nginx listens to port 80 by default. This EXPOSE instruction should indicate what ports are we gonna get our output from this Dockerfile.

2022-09-04 21:23 UTC, musfique-m commented on Todo-List-App/docker-composer.prod.yml
> +    stdin_open: true
Why are we running the container in interactive mode?

2022-09-04 21:23 UTC, musfique-m commented on Todo-List-App/docker-composer.prod.yml
> +      - CHOKIDAR_USEPOLLING=true
Why do we need to do this? We are not going to watch for file changes in production environment.

2022-09-05 07:39 UTC, D-sourav-M044 commented on Todo-List-App/Dockerfile.prod
> +COPY package.json .
Updated Code. [4999d99](https://github.com/CraftsmenLtd/coe-batch-q322/commit/4999d99522c541a8daa56ea9b2ce5b8224cf1280)

2022-09-05 07:40 UTC, D-sourav-M044 commented on Todo-List-App/docker-composer.prod.yml
> +      - CHOKIDAR_USEPOLLING=true
Removed the environment variable as it is unnecessary. [4999d99](https://github.com/CraftsmenLtd/coe-batch-q322/commit/4999d99522c541a8daa56ea9b2ce5b8224cf1280)

2022-09-05 07:40 UTC, D-sourav-M044 commented on Todo-List-App/docker-composer.prod.yml
> +    stdin_open: true
Updated code. [4999d99](https://github.com/CraftsmenLtd/coe-batch-q322/commit/4999d99522c541a8daa56ea9b2ce5b8224cf1280)

2022-09-05 07:41 UTC, D-sourav-M044 commented on Todo-List-App/Dockerfile.prod
> +EXPOSE 3000
Updated EXPOSE instruction. [1184340](https://github.com/CraftsmenLtd/coe-batch-q322/commit/1184340ca37e2a02f41c116ddb2a6c76483702a4)

2022-09-07 05:48 UTC, musfique-m approved these changes
Looks good.

2022-09-07 05:48 UTC, merged