graph ql query and mutation
CraftsmenLtd/coe-batch-q322 pull request #317
Opened 2022-08-31 13:32 UTC by hossainahmed18

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [x] Improvement
- [ ] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done

Serverless.yml file was changed for create apsync. necessary schema declared. Mapping templates describes how query and mutation will run

## How to test

- [x] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-01 14:43 UTC, hossainahmed18 commented on junayed-task/junayed-serverlesss-lambda/serverless.yml
> +          serviceRoleArn: { Fn::GetAtt: [DynamoDbTable, Arn] }
this is automatically handling by  serverless-appsync-plugin

2022-09-01 14:46 UTC, hossainahmed18 commented on junayed-task/junayed-serverlesss-lambda/schema.graphql
> +    gsi1sk:String
resolved with commit : https://github.com/CraftsmenLtd/coe-batch-q322/pull/317/commits/9f1b0eb124c5532e9b2af725358ce526203f6281

2022-09-01 14:46 UTC, hossainahmed18 commented on junayed-task/junayed-serverlesss-lambda/schema.graphql
> +}
Implemented query from lambda data source. Last time talking with you, you asked to create query only, that's why skipped mutation now.
commit: https://github.com/CraftsmenLtd/coe-batch-q322/pull/317/commits/9f1b0eb124c5532e9b2af725358ce526203f6281

2022-09-02 05:40 UTC, rkzico21 requested changes
Please see the latest feedback. Apart from that change extension for all the vtl templates from .txt to .vtl

2022-09-02 05:40 UTC, rkzico21 commented on junayed-task/junayed-serverlesss-lambda/schema.graphql
> +input searchActivity {
To make distinction between type and input it is better to define input name as SearchActivityInput. Also it seems you forgot to make it PascelCase.

2022-09-02 05:40 UTC, rkzico21 commented on junayed-task/junayed-serverlesss-lambda/schema.graphql
> +    gsi1sk:String
Please remove those as these are not required

2022-09-02 06:31 UTC, hossainahmed18 commented on junayed-task/junayed-serverlesss-lambda/schema.graphql
> +    gsi1sk:String
resolved with commit : https://github.com/CraftsmenLtd/coe-batch-q322/pull/317/commits/8daf14765040c805144e4355389eeb511b5b6178

2022-09-02 06:31 UTC, hossainahmed18 commented on junayed-task/junayed-serverlesss-lambda/schema.graphql
> +input searchActivity {
resolved with commit : https://github.com/CraftsmenLtd/coe-batch-q322/pull/317/commits/8daf14765040c805144e4355389eeb511b5b6178

2022-09-02 09:11 UTC, rkzico21 requested changes
Just one minor query. Other than that everything looks fine.

2022-09-02 09:11 UTC, rkzico21 commented on junayed-task/junayed-serverlesss-lambda/mapping-templates/createUserAvtivity-request-mapping-template.vtl
> +        "SK": $util.dynamodb.toDynamoDBJson("$ctx.args.input.user-ctx.args.input.uploadedTime"),
Does this work as intended or it should be something like
"${ctx.args.input.user}-${ctx.args.input.uploadedTime}"

2022-09-02 09:46 UTC, hossainahmed18 commented on junayed-task/junayed-serverlesss-lambda/mapping-templates/createUserAvtivity-request-mapping-template.vtl
> +        "SK": $util.dynamodb.toDynamoDBJson("$ctx.args.input.user-ctx.args.input.uploadedTime"),
It works without brackets. But will not work without dollar. I accidently I removed the dollar while removing brackets. sorry for that mistake. commit: https://github.com/CraftsmenLtd/coe-batch-q322/pull/317/commits/b5ef627a83f2b5ae2087aea75178e8b19d0dcfad

2022-09-02 09:56 UTC, rkzico21 approved these changes
Everything looks okay. Good work.

2022-09-02 09:56 UTC, merged