Daniel task/ffmpeg
CraftsmenLtd/coe-batch-q322 pull request #319
Opened 2022-08-31 18:33 UTC by mukutdanielroy

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)
File compress with ffmpeg lambda layer.
- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Added ffmpeg layer to lambda, compress file when mp4, webm file is uploaded.
## What was done

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-02 09:39 UTC, mhazad requested changes
Please address the feedback.

2022-09-02 09:39 UTC, mhazad commented on handler.py
> +    print(event)
What is the purpose of logging the full event?

2022-09-05 14:48 UTC, mukutdanielroy commented on handler.py
> +    print(event)
Please accept my apologies. It was not meant to be pushed.

2022-09-06 03:20 UTC, mhazad approved these changes
LGTM

2022-09-06 03:21 UTC, merged