polok task/graphql appsync dynamodb resolver
CraftsmenLtd/coe-batch-q322 pull request #320
Opened 2022-09-01 05:29 UTC by codefresher32

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- Query using graphql appsync dynamodb resolver

## What was done
- Added a appsync resource
- Used dynamodb resolver in the appsync
- Added lambda resolver in the appsync

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-01 09:22 UTC, rkzico21 requested changes
Please address the feedback below. Also add a version of query that uses lambda as resolver.

2022-09-01 14:58 UTC, codefresher32 commented on schema.graphql
> +}
Used PascelCase for type and input name and camelCase for property name...

2022-09-01 15:00 UTC, codefresher32 commented on schema.graphql
> +}
Added lambda resolver...

2022-09-02 05:46 UTC, rkzico21 commented on schema.graphql
> +  GetActivityInfoByLambda(customer: String!, user: String): [UserActivity]
Instead of providing number of parameters to the query define an input name GetActivityInput

2022-09-02 05:51 UTC, rkzico21 requested changes
Please have a look at the feedback.

2022-09-02 05:51 UTC, rkzico21 commented on handler.js
> +    }
There is too much if/else nesting in the code block. Please reduce nesting by splitting this portion into couple of functions for query and mutation.

2022-09-02 10:56 UTC, codefresher32 commented on schema.graphql
> +  GetActivityInfoByLambda(customer: String!, user: String): [UserActivity]
Created input type named GetActivityInput....

2022-09-02 10:57 UTC, codefresher32 commented on handler.js
> +    }
Divided the query and mutation part in the function...

2022-09-03 15:33 UTC, rkzico21 requested changes
Some minor feedback.  Please have a look.

2022-09-03 15:33 UTC, rkzico21 commented on handler.js
> +const queryIntoDynamoDBUsingAppSync = async (event) => {
It would be more appropriate to rename the function getActivities

2022-09-03 15:33 UTC, rkzico21 commented on handler.js
> +const mutationIntoDynamoDBUsingAppSync = async (event) => {
Rename it to createActivity(or addActivity)

2022-09-04 04:44 UTC, codefresher32 commented on handler.js
> +const queryIntoDynamoDBUsingAppSync = async (event) => {
renamed the query function...

2022-09-04 04:45 UTC, codefresher32 commented on handler.js
> +const mutationIntoDynamoDBUsingAppSync = async (event) => {
renamed the mutation function....

2022-09-08 03:53 UTC, codefresher32 commented
Please review this pr....

2022-09-15 09:38 UTC, rkzico21 approved these changes
Looks good.

2022-09-15 09:39 UTC, merged