Ecs fargate eftakhar
CraftsmenLtd/coe-batch-q322 pull request #325
Opened 2022-09-02 15:49 UTC by shoccho

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #324 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [x] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Added new functionality to convert the video files using a container from ECR via ECS tasks instead of lambda
## What was done
 - Added new Docker image creation files ( Docker files and shell scripts to push Image to ECR )
 - Added new ECS Task defination resource
 - Added new Task log group resource 
 - Added permissions to lambda to run ecs task and pass role
 - Added new Conversion mechanism with ecs tasks
 - Removed older video conversion mechanism code  
 - Included the terraform backend init script to initialize terraform deployment with s3 backend
 - 
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-05 06:13 UTC, mhazad requested changes
Please address the feedback.

2022-09-06 03:25 UTC, shoccho commented on converter/fileoperations.sh
> +aws s3 cp output.mp4 s3://$BUCKET_NAME/$OUTPUT_FILE_NAME
Implemented this in JavaScript in the commit [d8f9037](https://github.com/CraftsmenLtd/coe-batch-q322/pull/325/commits/d8f90376cec59f8c30900c2a5113014f9cad02ea)

2022-09-06 03:25 UTC, shoccho commented on serverless.yml
> +                    - "ecs:*"
Removed unnecessary permissions in this commit [c76fc9d](https://github.com/CraftsmenLtd/coe-batch-q322/pull/325/commits/c76fc9d2acf027513f112a87c413b8fcef53b3d1)

2022-09-06 05:00 UTC, mhazad approved these changes
LGTM

2022-09-06 05:00 UTC, merged