257 harun react todo app task2
CraftsmenLtd/coe-batch-q322 pull request #327
Opened 2022-09-02 18:26 UTC by ewuharun

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
added context api, reducers, and emotion
## What was done

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-19 08:28 UTC, tusher-A requested changes
Some serious issues with the code. Please look at them. If they are not resolved, I will not look the other PR. You must update the other PR with proper codes.

2022-09-19 08:28 UTC, tusher-A commented on src/App.js
> +}
This reducer here can be moved to the context folder as this is related to context. Please check other people's PR for inspiration.

2022-09-19 08:28 UTC, tusher-A commented on src/App.js
> +  }
Move this to context also.

2022-09-19 08:28 UTC, tusher-A commented on src/App.js
> +      <TodoContext.Provider value={{ todoList, dispatch }}>
Also the provider should be in the context folder.

2022-09-19 08:28 UTC, tusher-A commented on src/components/Input/TextInputField.js
> +
Do we need a reducer here? Just a simple useState should do. Please don't over-engineer.

2022-09-19 08:28 UTC, tusher-A commented on src/components/Input/TextInputField.js
> +  const [newTodo, dispatch] = useReducer(reducer, '');
Use simple `useState` here.

2022-09-19 08:28 UTC, tusher-A commented on src/components/Item/Item.js
> +    const [isMouseEntered, setIsMouseEntered] = useReducer(reducer, false);
Why use Reducer to keep a simple state? This is really bad coding practice and not expected at all. Please again, don't over-engineer stuff. Use a simple `useState` to do the work.

2022-09-19 08:28 UTC, tusher-A commented on src/components/Item/Item.js
> +const Item = (props) => {
Move this component to a separate folder. Even after saying the preferred way to organize folder and file, looking at this kind of dis-organized code is really frustrating.

2022-09-19 08:28 UTC, tusher-A commented on src/components/Item/styled/itemStyle.js
> +import styled from "@emotion/styled";
Why the `itemStyle` is on separate folder. You're moving files that should not be moved to separate folder and not moving the files that are needed. How many times do I have to say to maintain proper file and folder structure

2022-09-19 18:33 UTC, ewuharun commented on src/App.js
> +}
Done.

2022-09-19 18:33 UTC, ewuharun commented on src/App.js
> +  }
Done

2022-09-19 18:33 UTC, ewuharun commented on src/App.js
> +      <TodoContext.Provider value={{ todoList, dispatch }}>
Done

2022-09-19 18:34 UTC, ewuharun commented on src/components/Input/TextInputField.js
> +
It happens because of misscummunication. I thought that everything will be in reducer instead of useState. I have fixed it.

2022-09-19 18:35 UTC, ewuharun commented on src/components/Input/TextInputField.js
> +  const [newTodo, dispatch] = useReducer(reducer, '');
Used useState

2022-09-19 18:35 UTC, ewuharun commented on src/components/Item/Item.js
> +    const [isMouseEntered, setIsMouseEntered] = useReducer(reducer, false);
Done

2022-09-19 18:36 UTC, ewuharun commented on src/components/Item/Item.js
> +const Item = (props) => {
Instead of moving this Component I have renamed itemList.js to todoList.js and moved into separate folder. and Item component is in Item folder

2022-09-19 18:37 UTC, ewuharun commented on src/components/Item/styled/itemStyle.js
> +import styled from "@emotion/styled";
fixed it

2022-09-20 07:28 UTC, tusher-A approved these changes
LGTM

2022-09-20 07:29 UTC, merged