Doha - Terraform
CraftsmenLtd/coe-batch-q322 pull request #336
Opened 2022-09-05 03:14 UTC by DewDropsDoha

Fixes #

- [ ] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #202 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done
Implemented terraform

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-05 06:58 UTC, mhazad requested changes
Please address the feedback.

2022-09-05 06:58 UTC, mhazad commented on doha-aws-node-project/terraform/terraform-handler/terraform.js
> +"use strict";
Why we cannot reuse the same lambda code from serverless?

2022-09-05 06:58 UTC, mhazad commented on doha-aws-node-project/terraform/variables.tf
> +# }
What is the benefit of having commented out code here?

2022-09-05 06:58 UTC, mhazad commented on doha-aws-node-project/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Why you are using yarn here?

2022-09-05 08:58 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform-handler/terraform.js
> +"use strict";
At start,  I've started terrraform as different project from my master branch. But both serverless and terraform are same except [terraform: event?.requestContext?.httpMethod and serverless: event?.requestContext?.http?.Method].
To use serverless lambda code, I need to merge serverless branch with it. After fixing, i'll notify.

2022-09-05 09:18 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/variables.tf
> +# }
Removed commented-out code. I should avoid pushing multiple files at once.
I have problem in terraform.js so that too focused on that file. When fixed, removed unnecessary code from terraform.js then test then pushed.

2022-09-05 10:39 UTC, DewDropsDoha commented on doha-aws-node-project/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
yarn.lock removed. From now on, I'll use npm. Commit c7e18af

2022-09-05 13:15 UTC, mhazad requested changes
Please address the feedback.

2022-09-05 13:15 UTC, mhazad commented on doha-aws-node-project/terraform/terraform-handler/terraform.js
> +"use strict";
can't we use a simple check and reuse the existing code then?

2022-09-06 02:01 UTC, DewDropsDoha commented on doha-aws-node-project/terraform/terraform-handler/terraform.js
> +"use strict";
Reused sls lambda code in terraform. Commit: 9fb3c62

2022-09-06 04:55 UTC, mhazad approved these changes
LGTM

2022-09-06 04:58 UTC, merged