Fargate/Compress video with ECS
CraftsmenLtd/coe-batch-q322 pull request #345
Opened 2022-09-06 12:31 UTC by Awsaf780

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- Compress video with ECS Task

## What was done
- Add ECS execution role and policy
- Change default deployment bucket
- Create Task Definition resource in YAML
- Build docker image for compression logic

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-07 06:08 UTC, mhazad requested changes
Please address the feedback.

2022-09-07 06:08 UTC, mhazad commented on awsaf-serverless-engine/src/handler.js
> +    return sendResponseToClient(400, error);
Please explain with proper logic why do you think the error code should be 400?

2022-09-07 06:08 UTC, mhazad commented on fargate/package.json
> +      "compress": "run-func compress.js initiateCompression"
Why do we need run-func here? Do we really need a third-party library to execute our js file?

2022-09-07 06:08 UTC, mhazad commented on fargate/compress.js
> +        return sendResponseToClient(400, error);
Please explain with proper logic why do you think the error code should be 400?

2022-09-07 06:08 UTC, mhazad commented on fargate/compress.js
> +        return sendResponseToClient(400, error);
Please explain with proper logic why do you think the error code should be 400?

2022-09-09 05:23 UTC, Awsaf780 commented on awsaf-serverless-engine/src/handler.js
> +    return sendResponseToClient(400, error);
Resolved in commit - [f642467](https://github.com/CraftsmenLtd/coe-batch-q322/pull/345/commits/f64246799523b12299e1cfc721da8f26c88bbf08)
Mistake from my understanding of this concept. Will not happen again.

2022-09-09 05:23 UTC, Awsaf780 commented on fargate/compress.js
> +        return sendResponseToClient(400, error);
Resolved in commit - [f642467](https://github.com/CraftsmenLtd/coe-batch-q322/pull/345/commits/f64246799523b12299e1cfc721da8f26c88bbf08)

2022-09-09 05:23 UTC, Awsaf780 commented on fargate/compress.js
> +        return sendResponseToClient(400, error);
Resolved in commit - [f642467](https://github.com/CraftsmenLtd/coe-batch-q322/pull/345/commits/f64246799523b12299e1cfc721da8f26c88bbf08)

2022-09-09 05:24 UTC, Awsaf780 commented on fargate/package.json
> +      "compress": "run-func compress.js initiateCompression"
Resolved in commit - [12dd071](https://github.com/CraftsmenLtd/coe-batch-q322/pull/345/commits/12dd0711a529b7f8eea95a22452168cab28bda24)
Third-party library not needed. Node is enough.

2022-09-09 05:40 UTC, mhazad approved these changes
LGTM

2022-09-09 05:40 UTC, merged