Harun-dynamodb-query-6-usecase
CraftsmenLtd/coe-batch-q322 pull request #349
Opened 2022-09-06 21:43 UTC by ewuharun

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #145 

## What kind of change does this PR introduce (check at least one)
completed the dynamodb schema design 6 usecase query
- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done
Added the dynamo query code in PresignedUrlHandler.java and Deleted the TerraformLambdaHandler.java as it  violates the DRY principle
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-07 05:45 UTC, mhazad requested changes
I shall be very honest and straightforward with my feedback here. 

This PR is only supposed to deal with the DDB query task. However, it has code fragments from the terraform task which clearly indicates your inability to organize your code changes properly. 

You have done some refactoring of your code while implementing the DDB query task and it gives you a shameful opportunity to repeat your mistakes which is really disappointing to see.

I know that you are working hard and raising this PR around 3 AM at night, but hard work with a lack of proper focus, planning, and coordination will only make you exhausted. It's also not a great experience for me to see someone is not improving even after giving almost the same kind of feedback for the last 5 weeks. 

Unless you improve yourself magically, I have a serious doubt now if you are going to be fit for Craftsmen or not.  

I want this PR to be merged without any further feedback once you have addressed all the current feedback.

2022-09-07 05:45 UTC, mhazad commented on build.gradle
> +    implementation 'com.amazonaws:aws-java-sdk-ecs'
Why do we need ecs for ddb query task?

2022-09-07 05:45 UTC, mhazad commented on serverless.yml
> +            method: POST
This gives me the impression that you do not know anything about REST 🤦‍♂️😞.  Please explain with proper logic why you have used the POST method to get/fetch data?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                        .setStatusCode(200)
Still, you are sending 200 status code for an exception. You are repeating the same mistakes over and over again 😞 .

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                response = new Response("Api Error", message);
You haven't used `response` anywhere in this particular code block. What is your plan with this unused initialization?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    item.put("SK", new AttributeValue(userName + "#" + date));
It's a good practice to have a utility method to get the PK/SK/GsiPK/GsiSK like getPkOfCustomerActivity(), GetGsiSkOfCustomerActivity() etc

The benefit is that we shall get information about key formation from a single place so it will act as documentation. Also If we ever need to change any key formation in the future then we need to change it in a single place.

Please do the necessary refactoring to accommodate these changes throughout your implementation.

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +            ItemCollection<QueryOutcome> items = index.query(spec);
Missing defensive code: What will happen if index.query(spec) throws an exception?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = index.query(spec);
Missing defensive code: What will happen if index.query(spec) throws an exception?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
Missing defensive code: What will happen if index.query(spec) throws an exception?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
Missing defensive code: What will happen if index.query(spec) throws an exception?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
Missing defensive code: What will happen if index.query(spec) throws an exception?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/lambdas/TerraformLambda.java
> -package com.serverless.lambdas;
Why this file is deleted?

2022-09-07 05:45 UTC, mhazad commented on src/main/java/com/serverless/utility/Compress.java
> +    }
What is the purpose of this file in this particular PR?

2022-09-07 05:45 UTC, mhazad commented on terraform/ecs.tf
> +resource "aws_ecs_task_definition" "ecs_task" {
How this ecs.tf will help to do the DDB query task?

2022-09-07 05:45 UTC, mhazad commented on terraform/iam.tf
> +      },
How this code changes will help to do the DDB query task?

2022-09-07 05:45 UTC, mhazad commented on terraform/iam.tf
> +  }
How this code changes will help to do the DDB query task?

2022-09-07 05:45 UTC, mhazad commented on terraform/s3.tf
> +
How this code changes will help to do the DDB query task?

2022-09-07 05:45 UTC, mhazad commented on terraform/sqs.tf
> +        "Resource" : "arn:aws:sqs:*:*:${var.SQS_NAME}",
How these code changes will help to do the DDB query task?

2022-09-07 19:36 UTC, ewuharun commented on build.gradle
> +    implementation 'com.amazonaws:aws-java-sdk-ecs'
removed the ecs dependency

2022-09-07 19:37 UTC, ewuharun commented on serverless.yml
> +            method: POST
I have chnaged the method to GET and Passed the data as queryString parameter.

2022-09-07 19:37 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                        .setStatusCode(200)
I have fixed it

2022-09-07 19:37 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                response = new Response("Api Error", message);
I have fixed it

2022-09-07 19:38 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    item.put("SK", new AttributeValue(userName + "#" + date));
Done

2022-09-07 19:38 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +            ItemCollection<QueryOutcome> items = index.query(spec);
added defensive code

2022-09-07 19:38 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = index.query(spec);
added defensive code

2022-09-07 19:39 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
added defensive code

2022-09-07 19:39 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
added defensive code

2022-09-07 19:39 UTC, ewuharun commented on src/main/java/com/serverless/lambdas/PreSignedUrlHandler.java
> +                    ItemCollection<QueryOutcome> items = table.query(spec);
added defensive code

2022-09-07 19:41 UTC, ewuharun commented on src/main/java/com/serverless/utility/Compress.java
> +    }
Removed it

2022-09-07 19:44 UTC, ewuharun commented on terraform/ecs.tf
> +resource "aws_ecs_task_definition" "ecs_task" {
Basically I have opened the branch while doing the ecs task thats why i added the file. But now i have removed the file

2022-09-08 04:59 UTC, mhazad requested changes
Now the PR resembles that it is developed by an engineer and that now I can give feedback on the code quality. 

In the failure case, you have used the following code to return from the lambda.

```java
message = new HashMap<>();
message.put("Exception", e.getLocalizedMessage());
response = new Response("Api Executed With Exception", message);
return ApiGatewayResponse.builder()
        .setStatusCode(e.getStatusCode())
        .setObjectBody(response)
        .setHeaders(Collections.singletonMap("X-Powered-By", "AWS Lambda & serverless"))
        .build();
````
In the success case, you have used the following code to return from the lambda.
```java
message = new HashMap<>();
message.put("Success", "Data Inserted Successfully");
response = new Response("Api Executed", message);
return ApiGatewayResponse.builder()
        .setStatusCode(200)
        .setObjectBody(response)
        .setHeaders(Collections.singletonMap("X-Powered-By", "AWS Lambda & serverless"))
        .build();
````
It's almost the same piece of code being copied a number of times and thus violating the DRY principle. Can we have a utility method that will take do it regardless it is success and failure by taking the proper parameters?

2022-09-08 05:05 UTC, mhazad requested changes

2022-09-08 05:05 UTC, mhazad commented on src/main/java/com/serverless/utility/KeyUtil.java
> +        return "Customer#"+customerName;
This is feedback related to the best practice. 

It is always better to use StringBuilder.append then String+. For this particular case as it is a small operation so from a performance perspective both StringBuilder.append and string+ will have the same result. 

However when you will do a large string operation StringBuilder.append performance is always better than String+. So it is a good practice to use StringBuilder.append.

2022-09-08 06:51 UTC, ewuharun commented
> Now the PR resembles that it is developed by an engineer and that now I can give feedback on the code quality.
> 
> In the failure case, you have used the following code to return from the lambda.
> 
> ```java
> message = new HashMap<>();
> message.put("Exception", e.getLocalizedMessage());
> response = new Response("Api Executed With Exception", message);
> return ApiGatewayResponse.builder()
>         .setStatusCode(e.getStatusCode())
>         .setObjectBody(response)
>         .setHeaders(Collections.singletonMap("X-Powered-By", "AWS Lambda & serverless"))
>         .build();
> ```
> 
> In the success case, you have used the following code to return from the lambda.
> 
> ```java
> message = new HashMap<>();
> message.put("Success", "Data Inserted Successfully");
> response = new Response("Api Executed", message);
> return ApiGatewayResponse.builder()
>         .setStatusCode(200)
>         .setObjectBody(response)
>         .setHeaders(Collections.singletonMap("X-Powered-By", "AWS Lambda & serverless"))
>         .build();
> ```
> 
> It's almost the same piece of code being copied a number of times and thus violating the DRY principle. Can we have a utility method that will take do it regardless it is success and failure by taking the proper parameters?

added utility function in PresignedUrlHandler.java

2022-09-08 06:53 UTC, ewuharun commented on src/main/java/com/serverless/utility/KeyUtil.java
> +        return "Customer#"+customerName;
added String builder

2022-09-08 07:26 UTC, mhazad approved these changes
LGTM

2022-09-08 07:26 UTC, merged