Raiyan docker task2: nginx
CraftsmenLtd/coe-batch-q322 pull request #357
Opened 2022-09-07 10:45 UTC by raiyan-hosn

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #306 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

## What was done
Running react app in nginx server on docker container.
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-07 18:40 UTC, musfique-m requested changes
1. `package.json` and `package-lock.json` should not be a part of this pr. We are not updating any packages in this pr. So this changes should not be a part of this pr.
2. move the `docker-compose.prod.yml` to the same level as `docker-compose.yml`.
3. Remove comment from prod files.

2022-09-07 18:40 UTC, musfique-m commented on frontend/docker-compose.prod.yml
> +      stdin_open: true
Please remove this. We are not going to run our production container in interactive mode by default.

2022-09-08 05:24 UTC, raiyan-hosn commented on frontend/docker-compose.prod.yml
> +      stdin_open: true
Removed.

2022-09-08 05:24 UTC, raiyan-hosn commented
Removed package*.json and removed comments from prod files.

2022-09-11 15:31 UTC, musfique-m approved these changes
Looks good.

2022-09-11 15:32 UTC, merged