Sabbir task/trigger sqs on s3 event and save filename in ddb
CraftsmenLtd/coe-batch-q322 pull request #370
Opened 2022-09-08 07:35 UTC by sabbir80

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Introduced sqs, s3 event and dynamodb 
## What was done
trigger sqs on s3 put event and save the file name into dynamodb
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-08 11:21 UTC, mhazad requested changes
Good progress. I have some feedback that needs to be addressed.

2022-09-08 11:21 UTC, mhazad commented on firstLambda/handler.py
> +            rec = json.loads(records[0]['body'])['Records']
Missing Defensive code: We are receiving this event from the outside and it might happen that the records[0] may not have any "body" attribute or it might not have Records there. In both of these cases the code will crash. Please add the necessary code to do the check so that it does not crash.

2022-09-08 11:21 UTC, mhazad commented on firstLambda/handler.py
> +            object = rec[0]['s3']['object']['key']
Missing defensive code.

2022-09-08 13:13 UTC, sabbir80 commented on firstLambda/handler.py
> +            rec = json.loads(records[0]['body'])['Records']
addressed this modification in aa7d867

2022-09-08 13:13 UTC, sabbir80 commented on firstLambda/handler.py
> +            object = rec[0]['s3']['object']['key']
addressed this modification in aa7d867

2022-09-08 13:27 UTC, mhazad commented on firstLambda/handler.py
> +                        object = rec[0]['s3'].get('object').get('key')
Lack of defensive code. What will happen if get('object') returns nothing?

2022-09-08 17:29 UTC, sabbir80 commented on firstLambda/handler.py
> +                        object = rec[0]['s3'].get('object').get('key')
addressed the feedback in 0a7080d

2022-09-08 17:33 UTC, sabbir80 commented on firstLambda/handler.py
> +                        bucket = rec[0]['s3'].get('bucket').get('name')
It will appears to else and return a json dumps message

2022-09-09 04:29 UTC, mhazad approved these changes
LGTM

2022-09-09 04:30 UTC, merged