Nayem ddb query implementation
CraftsmenLtd/coe-batch-q322 pull request #371
Opened 2022-09-08 07:50 UTC by lucifer7663

Fixes #

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- implemented ddb user activity query
## What was done

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-08 08:04 UTC, mhazad requested changes
You are repeating mistakes. At the first glance, I found a code formatting issue. Please double-check your PR and only request for review when you will think that it's good to go.  Please do not waste your and my time for your negligence.

2022-09-08 08:04 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +                    }catch (Exception e){
😞 🤦‍♂️ Malformatted code!  
```java
}catch (Exception e){
```
Please check your PR again and fix all formatting issues.

2022-09-08 13:07 UTC, mhazad requested changes
The code is much better now.  I have given some more feedback that is related to using different conventions while defining various variables.  Please address these.

2022-09-08 13:07 UTC, mhazad commented on serverless.yml
> +    Table_Name: ${env:QUERYTABLENAME}
The code should follow a certain convention. Previous environment variables were declared as Pascal Case, but this one is defined as Pascal Snake Case.

2022-09-08 13:07 UTC, mhazad commented on serverless.yml
> +    baseUrl: ${env:BASEURL}
The code should follow a certain convention. Previous environment variables were declared as Pascal Case, but this one is defined as camel case.

2022-09-08 13:07 UTC, mhazad commented on serverless.yml
> +    webhook: ${env:WEBHOOK}
The code should follow a certain convention. Previous environment variables were declared as Pascal Case, but this one is defined as lower case.

2022-09-08 13:07 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +            if (params.containsKey("customerName") && params.containsKey("username") && params.containsKey("queryType")) {
The code should follow a certain convention. 
customerName is camelCase
username is lowercase
queryType is camelCase. 

username should be camelCase

2022-09-08 15:21 UTC, lucifer7663 commented on serverless.yml
> +    baseUrl: ${env:BASEURL}
variable naming convention is reverted to original Pascal Case.

2022-09-08 15:21 UTC, lucifer7663 commented on serverless.yml
> +    Table_Name: ${env:QUERYTABLENAME}
variable naming convention is reverted to original Pascal Case.

2022-09-08 15:21 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +            if (params.containsKey("customerName") && params.containsKey("username") && params.containsKey("queryType")) {
username is now in camleCase

2022-09-09 05:34 UTC, mhazad approved these changes
LGTM

2022-09-09 05:34 UTC, merged