fargate implementation
CraftsmenLtd/coe-batch-q322 pull request #372
Opened 2022-09-08 08:24 UTC by lucifer7663

Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #371 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [x] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
- implemented aws fargate for video compression
## What was done

## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

2022-09-08 08:52 UTC, mhazad requested changes
You are continuing to make the same mistakes. If you continue to do this then it will be nearly impossible for you to continue with us. Please be cautious with your keyboard and output.

2022-09-08 08:52 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +        if (input.containsKey("routeKey") && input.get("routeKey").equals("POST /insert")
"user-activity" was perfect as a resource. Why it is changed to "insert"?

2022-09-08 08:52 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +        if (input.containsKey("routeKey") && input.get("routeKey").equals("GET /query")
"user-activity" was perfect as a resource. Why it is changed to "query"?

2022-09-08 08:52 UTC, mhazad commented on src/main/java/com/serverless/Handler.java
> +                            ecs.runTask(request);
Where is your defensive code here? What will happen if this encounters an exception? You made similar mistakes earlier and proudly continuing it. Bravo! 👏

2022-09-08 09:36 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +        if (input.containsKey("routeKey") && input.get("routeKey").equals("POST /insert")
resolved the problem

2022-09-08 09:37 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +                            ecs.runTask(request);
introduced defensive code

2022-09-08 09:37 UTC, lucifer7663 commented on src/main/java/com/serverless/Handler.java
> +        if (input.containsKey("routeKey") && input.get("routeKey").equals("GET /query")
resolve the problem

2022-09-08 13:14 UTC, mhazad requested changes
Good attempt 👍  Please address the feedback.

2022-09-08 13:14 UTC, mhazad commented on src/main/java/com/serverless/CompressVideo.java
> +        String compressResult = compressVideos(fileName, bucketName);
BucketName is Pascal case and fileName is camel case. Please follow one single convention.

2022-09-08 13:19 UTC, mhazad commented
One more general feedback 

In the terraform file you have defined the environment variables like this
```tf
environment {
    variables = {
      nayem_bucket_name = var.nayem_bucket_name
      nayem_sns = var.nayem_sns
      nayem_sqs_name = var.nayem_sqs_name
      nayem_ddb_table = var.nayem_ddb_table
      clusterName = var.clusterName
      subnets = var.subnets
      container_definitions_name = var.container_definitions_name
      task_definition_name = var.task_definition_name
      container_image = var.container_image
    }
  }
```

And in the serverless.yml you have defined the environment variables like this

```yml
 environment:
    BucketName: ${env:BUCKETNAME}
    QueueName: ${env:QUEUENAME}
    TableName: ${env:TABLENAME}
    Table_Name: ${env:QUERYTABLENAME}
    TopicName: ${env:TOPICNAME}
    DisplayName: ${env:DISPLAYNAME}
    baseUrl: ${env:BASEURL}
    webhook: ${env:WEBHOOK}

```

Ideally, it should be the same as for the terraform it should be like below and then for this you do not need to change any code in the handler.java

```tf
      BucketName = var.nayem_bucket_name
      TopicName = var.nayem_sns
      QueueName = var.nayem_sqs_name
      TableName= var.nayem_ddb_table
```

2022-09-08 15:54 UTC, lucifer7663 commented on src/main/java/com/serverless/CompressVideo.java
> +        String compressResult = compressVideos(fileName, bucketName);
fileName is now in Pascal Case

2022-09-09 04:31 UTC, mhazad approved these changes
Now its look really good to me! Good Job and keep up the quality.

2022-09-09 04:31 UTC, merged